### ISSUE TITLE
Built-in `isBuiltin`

### ISSUE THREAD

**Issue by webpro** [sindresorhus/is-builtin-module#12]
FYI, Node.js v16.17.0 and v18.6.0 introduced [module.isBuiltin](https://nodejs.org/api/module.html#moduleisbuiltinmodulename), so when on bleeding edge we can import the _built-in_ `isBuiltin`:

```js
import { isBuiltin } from 'node:module';
```

**Comment by sindresorhus** [comment]
Thanks for letting me know. I'll be sure to deprecate this package in favor of that when Node.js 14 is no longer supported.

**Comment by sindresorhus** [comment]
This package is now repurposed to only check for using a static list of built-ins from the latest Node.js version, not from the current one. So this still has a purpose even with the built-in API.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/is-builtin-module/releases/tag/v4.0.0
