### ISSUE TITLE
Question: Should we consider `fs/promises` a builtin module?

### ISSUE THREAD

**Issue by fisker** [sindresorhus/is-builtin-module#5]
See title

**Comment by sindresorhus** [comment]
Yes, and all the other sub-exports, like `timers/promises`, etc.

We also need to add support for `node:` here.

**Comment by fisker** [comment]
I'll work on it.

Don't switch to ESM before fixing it, since we are going to use it in `eslint-plugin-unicorn` and ESLint rules don't support ESM. 😄

**Comment by sindresorhus** [comment]
> Don't switch to ESM before fixing it, since we are going to use it in eslint-plugin-unicorn and ESLint rules don't support ESM. 😄

👍
