### ISSUE TITLE
[bug] `string_decoder/` is not builtin

### ISSUE THREAD

**Issue by loynoir** [sindresorhus/is-builtin-module#7]
### CJS & ESM
CJS and ESM both think `string_decoder/` is [external](https://www.npmjs.com/package/string_decoder)

```txt
> require('string_decoder/')
Uncaught Error: Cannot find module 'string_decoder/'
```

```
> await import('string_decoder/')
Uncaught:
Error [ERR_MODULE_NOT_FOUND]:
```

### Actual
```txt
> isBuiltinModule = require('is-builtin-module');
> isBuiltinModule('string_decoder/')
true
```

### Expected
```txt
> isBuiltinModule = require('is-builtin-module');
> isBuiltinModule('string_decoder/')
false
```

### Related
```txt
> isBuiltinModule('string_decoder')
true
> isBuiltinModule('fs/promises')
true
```

**Comment by sindresorhus** [comment]
When https://github.com/sindresorhus/builtin-modules/issues/12 is fixed, we can remove https://github.com/sindresorhus/is-builtin-module/blob/819869f9a6b64dffc80ac5b39c26def695afaef4/index.js#L16-L19 and this issue will be fixed.

**Comment by papb** [comment]
https://github.com/sindresorhus/builtin-modules/pull/17
