### ISSUE TITLE
Parameter is not under sufficient condition

### ISSUE THREAD

**Issue by loynoir** [sindresorhus/is-builtin-module#8]
### Proposal
```ts
is-builtin-module(name:string, runtime?:TRuntime)
```

```ts
interface TRuntime {
  version?: string,
  module?: "import" | "require",
  name?: "node" | "deno",
}
```

### Motivation
`stream/web` is experiment but builtin module in node16 but not in node14.
```sh
$ docker run -it node:16
> require('stream/web').ReadableStream
[class ReadableStream]

$ docker run -it node:14
> require('stream/web').ReadableStream
Uncaught Error: Cannot find module 'stream/web'
```

And maybe there is or will be some modules
1. maybe: builtin for require but not for import
2. maybe: builtin for import but not for require

Besides, maybe good for if support `deno` runtime in the future.

**Comment by sindresorhus** [comment]
I don't have any plans to any of this. If you need it, I suggest making a new package. I prefer to keep this one simple and focused on the 95% use-case.
